Fix k5test minimum version requirement (#58)
* Fix k5test minimum version requirement

The test function test_set_password fails when run with k5test 0.10.3.

```
TypeError: MITRealm.start_kadmind() missing 1 required positional argument: 'env'
```

This is because it is running the start_kadmind method with no
arguments, but the env argument didn't become optional until k5test
0.10.4.  That is now the new minimum version for this test dependency.

https://github.com/jborean93/pykrb5/commit/4cbfe7d89345e779c5252c06a7ef411fa155d2fb
https://github.com/pythongssapi/k5test/commit/aa9cf871e34a636f34e1207e733271580a9a3418

* Added reason to k5test min

---------

Co-authored-by: Jordan Borean <jborean93@gmail.com>